# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Napctl < Formula
  desc "Local and edge Docker compute orchestrator with wake-on-request"
  homepage "https://github.com/yousef-muc/napctl"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yousef-muc/napctl/releases/download/v0.1.9/napctl_0.1.9_darwin_amd64.tar.gz"
      sha256 "c6c251b0ffb7a60cdb0c66571c6b1f7a57f710025088b076e8201203e20168b7"

      define_method(:install) do
        bin.install "napctl"
        bin.install "napd"
        (etc/"nap").mkpath
        return if (etc/"nap/nap.yaml").exist?

        (etc/"nap/nap.yaml").write <<~EOS
          agent:
            socket: /tmp/napd.sock

          nodes:
            local:
              type: local
              default: true
              socket: /tmp/napd.sock

          gateway:
            listen: 127.0.0.1:8787

          services: {}
        EOS
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yousef-muc/napctl/releases/download/v0.1.9/napctl_0.1.9_darwin_arm64.tar.gz"
      sha256 "d2d07300447fb574632087f39309cb28e698e4442b6aa4fd2e14d1f147ea3228"

      define_method(:install) do
        bin.install "napctl"
        bin.install "napd"
        (etc/"nap").mkpath
        return if (etc/"nap/nap.yaml").exist?

        (etc/"nap/nap.yaml").write <<~EOS
          agent:
            socket: /tmp/napd.sock

          nodes:
            local:
              type: local
              default: true
              socket: /tmp/napd.sock

          gateway:
            listen: 127.0.0.1:8787

          services: {}
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yousef-muc/napctl/releases/download/v0.1.9/napctl_0.1.9_linux_amd64.tar.gz"
      sha256 "26d80c450c5cc9123104860bb0d04ec076bcd2f022100ca83f7c68d4076a0ea3"
      define_method(:install) do
        bin.install "napctl"
        bin.install "napd"
        (etc/"nap").mkpath
        return if (etc/"nap/nap.yaml").exist?

        (etc/"nap/nap.yaml").write <<~EOS
          agent:
            socket: /tmp/napd.sock

          nodes:
            local:
              type: local
              default: true
              socket: /tmp/napd.sock

          gateway:
            listen: 127.0.0.1:8787

          services: {}
        EOS
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yousef-muc/napctl/releases/download/v0.1.9/napctl_0.1.9_linux_arm64.tar.gz"
      sha256 "742887c3655924cccfaa337100c2fbcfde994cd96dedbb6c878f1d185ea7313a"
      define_method(:install) do
        bin.install "napctl"
        bin.install "napd"
        (etc/"nap").mkpath
        return if (etc/"nap/nap.yaml").exist?

        (etc/"nap/nap.yaml").write <<~EOS
          agent:
            socket: /tmp/napd.sock

          nodes:
            local:
              type: local
              default: true
              socket: /tmp/napd.sock

          gateway:
            listen: 127.0.0.1:8787

          services: {}
        EOS
      end
    end
  end

  def caveats
    <<~EOS
      napctl installs both napctl and napd.

      Client-only use:
        napctl --help

      Local Docker workloads on this Mac:
        brew services start napctl

      Default config:
        #{etc}/nap/nap.yaml
    EOS
  end

  service do
    run [opt_bin/"napd", "--config", etc/"nap/nap.yaml", "--socket", "/tmp/napd.sock"]
    keep_alive true
    log_path var/"log/napd.log"
    error_log_path var/"log/napd.err.log"
  end

  test do
    system "#{bin}/napctl", "version"
    system "#{bin}/napd", "--version"
  end
end
