# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Napctl < Formula
  desc "Local and edge Docker compute orchestrator with wake-on-request"
  homepage "https://github.com/yousef-muc/napctl"
  version "0.1.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yousef-muc/napctl/releases/download/v0.1.22/napctl_0.1.22_darwin_amd64.tar.gz"
      sha256 "7b46bcd241f18affed6504fc128d660ccefa33d2d6dc9f31dde41868f5e99528"

      define_method(:install) do
        bin.install "napctl"
        bin.install "napd"
        (etc/"nap").mkpath
        return if (etc/"nap/nap.yaml").exist?

        (etc/"nap/nap.yaml").write <<~EOS
          agent:
            socket: /tmp/napd.sock

          nodes:
            local:
              type: local
              default: true
              socket: /tmp/napd.sock

          gateway:
            listen: 127.0.0.1:8787

          services: {}
        EOS
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yousef-muc/napctl/releases/download/v0.1.22/napctl_0.1.22_darwin_arm64.tar.gz"
      sha256 "92de2648f886cae29fde516c655610c31d5d79e1b2190934e5aa3fc61390e841"

      define_method(:install) do
        bin.install "napctl"
        bin.install "napd"
        (etc/"nap").mkpath
        return if (etc/"nap/nap.yaml").exist?

        (etc/"nap/nap.yaml").write <<~EOS
          agent:
            socket: /tmp/napd.sock

          nodes:
            local:
              type: local
              default: true
              socket: /tmp/napd.sock

          gateway:
            listen: 127.0.0.1:8787

          services: {}
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yousef-muc/napctl/releases/download/v0.1.22/napctl_0.1.22_linux_amd64.tar.gz"
      sha256 "02ac0c4999bc7fd95ef79233135c6f269fb75568e362f371d3977ebe02ed7118"
      define_method(:install) do
        bin.install "napctl"
        bin.install "napd"
        (etc/"nap").mkpath
        return if (etc/"nap/nap.yaml").exist?

        (etc/"nap/nap.yaml").write <<~EOS
          agent:
            socket: /tmp/napd.sock

          nodes:
            local:
              type: local
              default: true
              socket: /tmp/napd.sock

          gateway:
            listen: 127.0.0.1:8787

          services: {}
        EOS
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yousef-muc/napctl/releases/download/v0.1.22/napctl_0.1.22_linux_arm64.tar.gz"
      sha256 "d0284331ba67e212348f6f6f4b12957f01ec0eb7a3940eda164a63c3778d7ce2"
      define_method(:install) do
        bin.install "napctl"
        bin.install "napd"
        (etc/"nap").mkpath
        return if (etc/"nap/nap.yaml").exist?

        (etc/"nap/nap.yaml").write <<~EOS
          agent:
            socket: /tmp/napd.sock

          nodes:
            local:
              type: local
              default: true
              socket: /tmp/napd.sock

          gateway:
            listen: 127.0.0.1:8787

          services: {}
        EOS
      end
    end
  end

  def caveats
    <<~EOS
      napctl installs both napctl and napd.

      Client-only use:
        napctl --help

      Local Docker workloads on this Mac:
        brew services start napctl

      Default config:
        #{etc}/nap/nap.yaml
    EOS
  end

  service do
    run [opt_bin/"napd", "--config", etc/"nap/nap.yaml", "--socket", "/tmp/napd.sock"]
    keep_alive true
    log_path var/"log/napd.log"
    error_log_path var/"log/napd.err.log"
  end

  test do
    system "#{bin}/napctl", "version"
    system "#{bin}/napd", "--version"
  end
end
