# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Napctl < Formula
  desc "Local and edge Docker compute orchestrator with wake-on-request"
  homepage "https://github.com/yousef-muc/napctl"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yousef-muc/napctl/releases/download/v0.1.3/napctl_0.1.3_darwin_amd64.tar.gz"
      sha256 "4c81bdfb3ebf91795989b95ec71bc80791f50a7d7a73ba5b178abe284f25aad5"

      define_method(:install) do
        bin.install "napctl"
        bin.install "napd"
        (etc/"nap").mkpath
        return if (etc/"nap/nap.yaml").exist?

        (etc/"nap/nap.yaml").write <<~EOS
          agent:
            socket: /tmp/napd.sock

          nodes:
            local:
              type: local
              default: true
              socket: /tmp/napd.sock

          gateway:
            listen: 127.0.0.1:8787

          services: {}
        EOS
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yousef-muc/napctl/releases/download/v0.1.3/napctl_0.1.3_darwin_arm64.tar.gz"
      sha256 "b02f523c4e1d89c03065b3b69d25771e55482d4515fd7b513474cb761d28dd15"

      define_method(:install) do
        bin.install "napctl"
        bin.install "napd"
        (etc/"nap").mkpath
        return if (etc/"nap/nap.yaml").exist?

        (etc/"nap/nap.yaml").write <<~EOS
          agent:
            socket: /tmp/napd.sock

          nodes:
            local:
              type: local
              default: true
              socket: /tmp/napd.sock

          gateway:
            listen: 127.0.0.1:8787

          services: {}
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yousef-muc/napctl/releases/download/v0.1.3/napctl_0.1.3_linux_amd64.tar.gz"
      sha256 "6c6f81058d1368202c9836494f10fa20a0adf9d13ce2e9b0dc765c1dbc70cd4e"
      define_method(:install) do
        bin.install "napctl"
        bin.install "napd"
        (etc/"nap").mkpath
        return if (etc/"nap/nap.yaml").exist?

        (etc/"nap/nap.yaml").write <<~EOS
          agent:
            socket: /tmp/napd.sock

          nodes:
            local:
              type: local
              default: true
              socket: /tmp/napd.sock

          gateway:
            listen: 127.0.0.1:8787

          services: {}
        EOS
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yousef-muc/napctl/releases/download/v0.1.3/napctl_0.1.3_linux_arm64.tar.gz"
      sha256 "b4ed7a0022b8ebe325fd913ac43d9ce7eda2614ed4c1aa4b986a0354fd9e15fd"
      define_method(:install) do
        bin.install "napctl"
        bin.install "napd"
        (etc/"nap").mkpath
        return if (etc/"nap/nap.yaml").exist?

        (etc/"nap/nap.yaml").write <<~EOS
          agent:
            socket: /tmp/napd.sock

          nodes:
            local:
              type: local
              default: true
              socket: /tmp/napd.sock

          gateway:
            listen: 127.0.0.1:8787

          services: {}
        EOS
      end
    end
  end

  def caveats
    <<~EOS
      napctl installs both napctl and napd.

      Client-only use:
        napctl --help

      Local Docker workloads on this Mac:
        brew services start napctl

      Default config:
        #{etc}/nap/nap.yaml
    EOS
  end

  service do
    run [opt_bin/"napd", "--config", etc/"nap/nap.yaml", "--socket", "/tmp/napd.sock"]
    keep_alive true
    log_path var/"log/napd.log"
    error_log_path var/"log/napd.err.log"
  end

  test do
    system "#{bin}/napctl", "version"
    system "#{bin}/napd", "--version"
  end
end
