# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portp2p < Formula
  desc "Secure one-port localhost sharing over libp2p"
  homepage "https://github.com/yousef-muc/portp2p"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yousef-muc/portp2p/releases/download/v1.3.0/portp2p_1.3.0_darwin_amd64.tar.gz"
      sha256 "17efbc6ad0c89254d1044fc982614442c7253ac18c9861165631a1b7ae366fa1"

      define_method(:install) do
        bin.install "portp2p"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yousef-muc/portp2p/releases/download/v1.3.0/portp2p_1.3.0_darwin_arm64.tar.gz"
      sha256 "9ec7c31b735c6d1ab8fe47916f50ab6d40c66b9f10e8b75f524f6371b5a6bc8f"

      define_method(:install) do
        bin.install "portp2p"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yousef-muc/portp2p/releases/download/v1.3.0/portp2p_1.3.0_linux_amd64.tar.gz"
      sha256 "c60505764ac17e981f5d6579b5abd0887e3d5f10dd497a48d335331fc9fd86a0"
      define_method(:install) do
        bin.install "portp2p"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yousef-muc/portp2p/releases/download/v1.3.0/portp2p_1.3.0_linux_arm64.tar.gz"
      sha256 "62510bff4afa2d0c60286a89db520ed6997d278a0a68abcd2ca38abf01a39894"
      define_method(:install) do
        bin.install "portp2p"
      end
    end
  end

  test do
    system "#{bin}/portp2p", "version"
  end
end
