# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portp2p < Formula
  desc "Secure one-port localhost sharing over libp2p"
  homepage "https://github.com/yousef-muc/portp2p"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yousef-muc/portp2p/releases/download/v1.2.1/portp2p_1.2.1_darwin_amd64.tar.gz"
      sha256 "697b4df4f43ec0da0bc6de6cc1fa64eca37ca8d8ac7a54ee5ad91c8b112b6d48"

      define_method(:install) do
        bin.install "portp2p"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yousef-muc/portp2p/releases/download/v1.2.1/portp2p_1.2.1_darwin_arm64.tar.gz"
      sha256 "c5bca50425166286e0f9d26ea397ffbf10c79baef20f4ca152c1b65366501e8b"

      define_method(:install) do
        bin.install "portp2p"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yousef-muc/portp2p/releases/download/v1.2.1/portp2p_1.2.1_linux_amd64.tar.gz"
      sha256 "b705166827d15ee30e55815c4184bf8184225faf39a9a8fc4c7244b18ba8b083"
      define_method(:install) do
        bin.install "portp2p"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yousef-muc/portp2p/releases/download/v1.2.1/portp2p_1.2.1_linux_arm64.tar.gz"
      sha256 "74e8c71410b281673763f502cd4c88bc61be82aaede9c846e41886e196ff9ea4"
      define_method(:install) do
        bin.install "portp2p"
      end
    end
  end

  test do
    system "#{bin}/portp2p", "version"
  end
end
