# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portp2p < Formula
  desc "Secure one-port localhost sharing over libp2p"
  homepage "https://github.com/yousef-muc/portp2p"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yousef-muc/portp2p/releases/download/v1.1.0/portp2p_1.1.0_darwin_amd64.tar.gz"
      sha256 "2beef8eca7b2552bdd15ea667d65ce8ea3fd65a694a0fdcdad99af3f0faeb5b8"

      define_method(:install) do
        bin.install "portp2p"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yousef-muc/portp2p/releases/download/v1.1.0/portp2p_1.1.0_darwin_arm64.tar.gz"
      sha256 "9215b4514a87d60e68d30f94e6bbf76a741b3b7df07f8ecb96843eca7ffe7819"

      define_method(:install) do
        bin.install "portp2p"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yousef-muc/portp2p/releases/download/v1.1.0/portp2p_1.1.0_linux_amd64.tar.gz"
      sha256 "59ecf912e18f305cfb99ecd2bea8f9c90882dae30faa2b1b9fac1fea37dca7a5"
      define_method(:install) do
        bin.install "portp2p"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yousef-muc/portp2p/releases/download/v1.1.0/portp2p_1.1.0_linux_arm64.tar.gz"
      sha256 "876b191fe3dbfbfcf7722db5fb7db3b9f0a18aa44a0755d9caa028d437a06bcc"
      define_method(:install) do
        bin.install "portp2p"
      end
    end
  end

  test do
    system "#{bin}/portp2p", "version"
  end
end
